Controllers/ProductsController.cs
using FillPizzaShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FillPizzaShop.Controllers
{
    public class ProductsController : Controller
    {
        private PizzaContext _db;
        public ProductsController(PizzaContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            var user = _db.UserAccounts.FirstOrDefault(i=>i.Email==User.Identity.Name);
            var Products = _db.Products.ToList();
            if (User.HasClaim(i => i.Type == "userType" && i.Value == "golden"))
            {
                float discount = 0;
                foreach (var item in Products.Where(i=>i.HasDiscount))
                {
                    discount = (item.Price * item.Discount) / 100;
                    item.Price -= discount;
                }
                return View(Products);
            }
            else return View(Products);
            
        }
        [HttpGet]
        public async Task<IActionResult> Details(int?id)
        {
            var product = await _db.Products.FirstOrDefaultAsync(i => i.Id == id);
            if (User.HasClaim(i => i.Type == "userType" && i.Value == "golden")&&product.HasDiscount)
            {
                product.Price = product.Price-(product.Price * product.Discount / 100);
            }
            return View(await _db.Products.FirstOrDefaultAsync(i=>i.Id==id));
        }
        [HttpPost]
        public async Task<IActionResult> Details(Product product)
        {
            var findProduct = await _db.Products.FirstOrDefaultAsync(i=>i.Id==product.Id);          
            findProduct.Salt = product.Salt;
            findProduct.Cheese = product.Cheese;
            ShopCart shopCart = new ShopCart
            {
                Product = findProduct,
                OrderId = _db.Orders.OrderBy(i => i).LastOrDefault().Id,
                TotalPrice=findProduct.Price
            };

            var ShopCardContain = _db.ShopCart.Include(i => i.Product).FirstOrDefault(i => i.Product.Name == findProduct.Name);

            if (ShopCardContain != null)
            {
                ShopCardContain.Count++;
                _db.ShopCart.Update(ShopCardContain);
                _db.SaveChanges();
            }
            else
            {
                shopCart.Count = 1;
                _db.ShopCart.Add(shopCart);
                _db.SaveChanges();
            }

            return RedirectToAction("Index");

        }   
    }
}

Controllers/ShopCartController.cs
using FillPizzaShop.Models;
using FillPizzaShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FillPizzaShop.Controllers
{
    public class ShopCartController : Controller
    {
        private PizzaContext _db;
        public ShopCartController(PizzaContext context)
        {
            _db = context;
        }
        public  IActionResult Index()
        {
            IEnumerable<ShopCart> shopCarts = _db.ShopCart.Include(i=>i.Product);
            foreach (var item in shopCarts)
            {
                if (User.HasClaim(i => i.Type == "userType" && i.Value == "golden"))
                {
                    item.Product.Price = item.Product.Price - (item.Product.Price * item.Product.Discount / 100);
                }
                item.TotalPrice = item.Count * item.Product.Price;
            }
            return View(shopCarts);
        }
        [HttpGet]
        public IActionResult CreateOrder()
        {
            if (User.Identity.IsAuthenticated)
            {
                var findUser = _db.UserAccounts.FirstOrDefault(i=>i.Email==User.Identity.Name);
                return View(new UserModel { 
                Name=findUser.Name,
                Phone=findUser.Phone
                });
            }
            return View();
        }
        [HttpPost]
        public IActionResult CreateOrder(UserModel user)
        {
            float OrderPrice = 0; 
            var shopCart = _db.ShopCart.Include(i => i.Product);
            List<OrderDetail> details = new List<OrderDetail>();
            foreach (var item in shopCart)
            {
                var currentItemPrice = item.TotalPrice * item.Count;
                    var OrderDetailsToAdd = new OrderDetail
                    {
                        ProductName = item.Product.Name,
                        ProductCount = item.Count,
                    };
                if (item.Product.Cheese)
                {
                    OrderDetailsToAdd.ProductAdditionals += "Cheese ";
                    currentItemPrice += 35;
                }
                if (item.Product.Salt)
                {
                    OrderDetailsToAdd.ProductAdditionals += "Salt ";
                    currentItemPrice += 15;
                } 
                 OrderPrice += currentItemPrice-(currentItemPrice*item.Product.Discount/100);
                OrderDetailsToAdd.Price=currentItemPrice;
                details.Add(OrderDetailsToAdd);
            }
         
            Order order = new Order
            {
                Date = DateTime.Now,
                OrderDetails = details,
                User = user,
                OrderPrice = OrderPrice
            };

            _db.Orders.Add(order);
            _db.SaveChanges();
            _db.ShopCart.RemoveRange(_db.ShopCart);
            _db.SaveChanges();
            return RedirectToAction("Index","Products");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var shopCartItem = await _db.ShopCart.FirstOrDefaultAsync(i=>i.Id==id);
            if (shopCartItem.Count > 1)
            {
                shopCartItem.Count -= 1;
                _db.SaveChanges();
            }
            else
            {
                _db.ShopCart.Remove(shopCartItem);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
      
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FillPizzaShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <style>
        .r-link {
            display: var(--rLinkDisplay, inline-flex) !important;
        }

            .r-link[href] {
                color: var(--rLinkColor) !important;
                text-decoration: var(--rLinkTextDecoration, none) !important;
            }

        .r-list {
            padding-left: var(--rListPaddingLeft, 0) !important;
            margin-top: var(--rListMarginTop, 0) !important;
            margin-bottom: var(--rListMarginBottom, 0) !important;
            list-style: var(--rListListStyle, none) !important;
        }
        /*
        =====
        CORE STYLES
        =====
        */
        .menu {
            --rLinkColor: var(--menuLinkColor, currentColor);
        }

        .menu__link {
            display: var(--menuLinkDisplay, block);
        }
            /*
        focus state
        */
            .menu__link:focus {
                outline: var(--menuLinkOutlineWidth, 2px) solid var(--menuLinkOutlineColor, currentColor);
                outline-offset: var(--menuLinkOutlineOffset);
            }
        /*
        fading siblings
        */
        .menu:hover .menu__link:not(:hover) {
            --rLinkColor: var(--menuLinkColorUnactive, rgba(22, 22, 22, .35));
        }
        /*
        =====
        PRESENTATION STYLES
        =====
        */
        .menu {
            background-color: var(--menuBackgroundColor, #f0f0f0);
            box-shadow: var(--menuBoxShadow, 0 1px 3px 0 rgba(0, 0, 0, .12), 0 1px 2px 0 rgba(0, 0, 0, .24));
        }

        .menu__list {
            display: flex;
        }

        .menu__link {
            padding: var(--menuLinkPadding, 1.5rem 2.5rem);
            font-weight: 700;
            text-transform: uppercase;
        }
        /*
        =====
        TEXT UNDERLINED
        =====
        */
        .text-underlined {
            position: relative;
            overflow: hidden;
            will-change: color;
            transition: color .25s ease-out;
        }

            .text-underlined::before,
            .text-underlined::after {
                content: "";
                width: 0;
                height: 3px;
                background-color: var(--textUnderlinedLineColor, currentColor);
                will-change: width;
                transition: width .1s ease-out;
                position: absolute;
                bottom: 0;
            }

            .text-underlined::before {
                left: 50%;
                transform: translateX(-50%);
            }

            .text-underlined::after {
                right: 50%;
                transform: translateX(50%);
            }

            .text-underlined:hover::before,
            .text-underlined:hover::after {
                width: 100%;
                transition-duration: .2s;
            }
        /*
        =====
        SETTINGS
        =====
        */
        .page__custom-settings {
            --menuBackgroundColor: #6c5ce7;
            --menuLinkColor: #fff;
            --menuLinkColorUnactive: #241c69;
            --menuLinkOutlineOffset: -.5rem;
        }
        /*
        =====
        DEMO
        =====
        */
        body {
            font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Open Sans, Ubuntu, Fira Sans, Helvetica Neue, sans-serif;
            margin: 0;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        .page {
            box-sizing: border-box;
            max-width: 640px;
            padding-left: .75rem;
            padding-right: .75rem;
            margin: auto;
        }

        .page__menu:nth-child(n+2) {
            margin-top: 3rem;
        }

        .substack {
            border: 1px solid #EEE;
            background-color: #fff;
            width: 100%;
            max-width: 480px;
            height: 280px;
            margin: 1rem auto;
        }
    </style>
    <header>
        <div class="page" style="display:flex;justify-content:center">
            <nav class="page__menu page__custom-settings menu">
                <ul class="menu__list r-list">
                    @if (User.IsInRole("admin"))
                    {
                        <li class="menu__group"><a asp-action="Index" asp-controller="Admin" class="menu__link r-link text-underlined">Admin</a></li>

                    }
                    <li class="menu__group"><a asp-action="Index" asp-controller="Home" class="menu__link r-link text-underlined">Home</a></li>
                    <li class="menu__group"><a asp-action="Index" asp-controller="Products" class="menu__link r-link text-underlined">Products</a></li>
                    <li class="menu__group"><a asp-action="Index" asp-controller="ShopCart" class="menu__link r-link text-underlined">ShopCard</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="menu__group"><a asp-action="Logout" asp-controller="Account" class="menu__link r-link text-underlined">Logout</a></li>
                    }
                    else
                    {
                        <li class="menu__group"><a asp-action="Login" asp-controller="Account" class="menu__link r-link text-underlined">Login</a></li>

                    }
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>